---
# tasks file for docker_compose

- name: install docker-compose package
  package:
    name: docker-compose
    state: present
  when:
    - not (ansible_distribution in ["RedHat", "CentOS"] and
      ansible_distribution_major_version == "8")
    - ansible_distribution != "Amazon"

- name: install docker-compose binary
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: "0755"
  when:
    - (ansible_distribution in ["RedHat", "CentOS"] and
      ansible_distribution_major_version == "8") or
      ansible_distribution == "Amazon"
