---
# tasks file for docker_compose

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install docker-compose
  block:
    - name: install docker-compose package
      package:
        name: docker-compose
        state: present

  rescue:
    - name: install docker-compose binary
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"
